/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogTheCrossedQuillsRouteImport } from './routes/blog/the-crossed-quills'
import { Route as BlogStrikeEmotionalChordRouteImport } from './routes/blog/strike-emotional-chord'
import { Route as BlogSpotTheWeaknessRouteImport } from './routes/blog/spot-the-weakness'
import { Route as BlogReadAnyRoomRouteImport } from './routes/blog/read-any-room'
import { Route as BlogMakeItStickRouteImport } from './routes/blog/make-it-stick'
import { Route as BlogLandTheCloserRouteImport } from './routes/blog/land-the-closer'
import { Route as BlogFlipTheirMomentumRouteImport } from './routes/blog/flip-their-momentum'
import { Route as BlogDefuseWithHumorRouteImport } from './routes/blog/defuse-with-humor'
import { Route as BlogCutThroughTheNoiseRouteImport } from './routes/blog/cut-through-the-noise'
import { Route as BlogBlueprintPart3RouteImport } from './routes/blog/blueprint-part-3'
import { Route as BlogBlueprintPart2RouteImport } from './routes/blog/blueprint-part-2'
import { Route as BlogBlueprintPart1RouteImport } from './routes/blog/blueprint-part-1'
import { Route as BlogBackItUpRouteImport } from './routes/blog/back-it-up'
import { Route as BlogAskTheKillerQuestionRouteImport } from './routes/blog/ask-the-killer-question'
import { Route as AppAuthRouteImport } from './routes/_app/_auth'
import { Route as AppLoginLayoutRouteImport } from './routes/_app/login/_layout'
import { Route as AppLoginLayoutIndexRouteImport } from './routes/_app/login/_layout.index'
import { Route as AppAuthOnboardingLayoutRouteImport } from './routes/_app/_auth/onboarding/_layout'
import { Route as AppAuthDashboardPrepRouteImport } from './routes/_app/_auth/dashboard/prep'
import { Route as AppAuthDashboardOpponentProfileRouteImport } from './routes/_app/_auth/dashboard/opponent-profile'
import { Route as AppAuthDashboardHistoryRouteImport } from './routes/_app/_auth/dashboard/history'
import { Route as AppAuthDashboardDebateRouteImport } from './routes/_app/_auth/dashboard/debate'
import { Route as AppAuthDashboardAnalysisRouteImport } from './routes/_app/_auth/dashboard/analysis'
import { Route as AppAuthDashboardLayoutRouteImport } from './routes/_app/_auth/dashboard/_layout'
import { Route as AppAuthDashboardLayoutIndexRouteImport } from './routes/_app/_auth/dashboard/_layout.index'
import { Route as AppAuthOnboardingLayoutUsernameRouteImport } from './routes/_app/_auth/onboarding/_layout.username'
import { Route as AppAuthDashboardLayoutSettingsRouteImport } from './routes/_app/_auth/dashboard/_layout.settings'
import { Route as AppAuthDashboardLayoutCheckoutRouteImport } from './routes/_app/_auth/dashboard/_layout.checkout'
import { Route as AppAuthDashboardLayoutSettingsIndexRouteImport } from './routes/_app/_auth/dashboard/_layout.settings.index'
import { Route as AppAuthDashboardLayoutSettingsBillingRouteImport } from './routes/_app/_auth/dashboard/_layout.settings.billing'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogTheCrossedQuillsRoute = BlogTheCrossedQuillsRouteImport.update({
  id: '/blog/the-crossed-quills',
  path: '/blog/the-crossed-quills',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogStrikeEmotionalChordRoute =
  BlogStrikeEmotionalChordRouteImport.update({
    id: '/blog/strike-emotional-chord',
    path: '/blog/strike-emotional-chord',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogSpotTheWeaknessRoute = BlogSpotTheWeaknessRouteImport.update({
  id: '/blog/spot-the-weakness',
  path: '/blog/spot-the-weakness',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogReadAnyRoomRoute = BlogReadAnyRoomRouteImport.update({
  id: '/blog/read-any-room',
  path: '/blog/read-any-room',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogMakeItStickRoute = BlogMakeItStickRouteImport.update({
  id: '/blog/make-it-stick',
  path: '/blog/make-it-stick',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogLandTheCloserRoute = BlogLandTheCloserRouteImport.update({
  id: '/blog/land-the-closer',
  path: '/blog/land-the-closer',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogFlipTheirMomentumRoute = BlogFlipTheirMomentumRouteImport.update({
  id: '/blog/flip-their-momentum',
  path: '/blog/flip-their-momentum',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogDefuseWithHumorRoute = BlogDefuseWithHumorRouteImport.update({
  id: '/blog/defuse-with-humor',
  path: '/blog/defuse-with-humor',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCutThroughTheNoiseRoute = BlogCutThroughTheNoiseRouteImport.update({
  id: '/blog/cut-through-the-noise',
  path: '/blog/cut-through-the-noise',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogBlueprintPart3Route = BlogBlueprintPart3RouteImport.update({
  id: '/blog/blueprint-part-3',
  path: '/blog/blueprint-part-3',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogBlueprintPart2Route = BlogBlueprintPart2RouteImport.update({
  id: '/blog/blueprint-part-2',
  path: '/blog/blueprint-part-2',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogBlueprintPart1Route = BlogBlueprintPart1RouteImport.update({
  id: '/blog/blueprint-part-1',
  path: '/blog/blueprint-part-1',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogBackItUpRoute = BlogBackItUpRouteImport.update({
  id: '/blog/back-it-up',
  path: '/blog/back-it-up',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAskTheKillerQuestionRoute =
  BlogAskTheKillerQuestionRouteImport.update({
    id: '/blog/ask-the-killer-question',
    path: '/blog/ask-the-killer-question',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppAuthRoute = AppAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginLayoutRoute = AppLoginLayoutRouteImport.update({
  id: '/login/_layout',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginLayoutIndexRoute = AppLoginLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLoginLayoutRoute,
} as any)
const AppAuthOnboardingLayoutRoute = AppAuthOnboardingLayoutRouteImport.update({
  id: '/onboarding/_layout',
  path: '/onboarding',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthDashboardPrepRoute = AppAuthDashboardPrepRouteImport.update({
  id: '/dashboard/prep',
  path: '/dashboard/prep',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthDashboardOpponentProfileRoute =
  AppAuthDashboardOpponentProfileRouteImport.update({
    id: '/dashboard/opponent-profile',
    path: '/dashboard/opponent-profile',
    getParentRoute: () => AppAuthRoute,
  } as any)
const AppAuthDashboardHistoryRoute = AppAuthDashboardHistoryRouteImport.update({
  id: '/dashboard/history',
  path: '/dashboard/history',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthDashboardDebateRoute = AppAuthDashboardDebateRouteImport.update({
  id: '/dashboard/debate',
  path: '/dashboard/debate',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthDashboardAnalysisRoute =
  AppAuthDashboardAnalysisRouteImport.update({
    id: '/dashboard/analysis',
    path: '/dashboard/analysis',
    getParentRoute: () => AppAuthRoute,
  } as any)
const AppAuthDashboardLayoutRoute = AppAuthDashboardLayoutRouteImport.update({
  id: '/dashboard/_layout',
  path: '/dashboard',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthDashboardLayoutIndexRoute =
  AppAuthDashboardLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthOnboardingLayoutUsernameRoute =
  AppAuthOnboardingLayoutUsernameRouteImport.update({
    id: '/username',
    path: '/username',
    getParentRoute: () => AppAuthOnboardingLayoutRoute,
  } as any)
const AppAuthDashboardLayoutSettingsRoute =
  AppAuthDashboardLayoutSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthDashboardLayoutCheckoutRoute =
  AppAuthDashboardLayoutCheckoutRouteImport.update({
    id: '/checkout',
    path: '/checkout',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthDashboardLayoutSettingsIndexRoute =
  AppAuthDashboardLayoutSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAuthDashboardLayoutSettingsRoute,
  } as any)
const AppAuthDashboardLayoutSettingsBillingRoute =
  AppAuthDashboardLayoutSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AppAuthDashboardLayoutSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog/ask-the-killer-question': typeof BlogAskTheKillerQuestionRoute
  '/blog/back-it-up': typeof BlogBackItUpRoute
  '/blog/blueprint-part-1': typeof BlogBlueprintPart1Route
  '/blog/blueprint-part-2': typeof BlogBlueprintPart2Route
  '/blog/blueprint-part-3': typeof BlogBlueprintPart3Route
  '/blog/cut-through-the-noise': typeof BlogCutThroughTheNoiseRoute
  '/blog/defuse-with-humor': typeof BlogDefuseWithHumorRoute
  '/blog/flip-their-momentum': typeof BlogFlipTheirMomentumRoute
  '/blog/land-the-closer': typeof BlogLandTheCloserRoute
  '/blog/make-it-stick': typeof BlogMakeItStickRoute
  '/blog/read-any-room': typeof BlogReadAnyRoomRoute
  '/blog/spot-the-weakness': typeof BlogSpotTheWeaknessRoute
  '/blog/strike-emotional-chord': typeof BlogStrikeEmotionalChordRoute
  '/blog/the-crossed-quills': typeof BlogTheCrossedQuillsRoute
  '/blog': typeof BlogIndexRoute
  '/login': typeof AppLoginLayoutRouteWithChildren
  '/dashboard': typeof AppAuthDashboardLayoutRouteWithChildren
  '/dashboard/analysis': typeof AppAuthDashboardAnalysisRoute
  '/dashboard/debate': typeof AppAuthDashboardDebateRoute
  '/dashboard/history': typeof AppAuthDashboardHistoryRoute
  '/dashboard/opponent-profile': typeof AppAuthDashboardOpponentProfileRoute
  '/dashboard/prep': typeof AppAuthDashboardPrepRoute
  '/onboarding': typeof AppAuthOnboardingLayoutRouteWithChildren
  '/login/': typeof AppLoginLayoutIndexRoute
  '/dashboard/checkout': typeof AppAuthDashboardLayoutCheckoutRoute
  '/dashboard/settings': typeof AppAuthDashboardLayoutSettingsRouteWithChildren
  '/onboarding/username': typeof AppAuthOnboardingLayoutUsernameRoute
  '/dashboard/': typeof AppAuthDashboardLayoutIndexRoute
  '/dashboard/settings/billing': typeof AppAuthDashboardLayoutSettingsBillingRoute
  '/dashboard/settings/': typeof AppAuthDashboardLayoutSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog/ask-the-killer-question': typeof BlogAskTheKillerQuestionRoute
  '/blog/back-it-up': typeof BlogBackItUpRoute
  '/blog/blueprint-part-1': typeof BlogBlueprintPart1Route
  '/blog/blueprint-part-2': typeof BlogBlueprintPart2Route
  '/blog/blueprint-part-3': typeof BlogBlueprintPart3Route
  '/blog/cut-through-the-noise': typeof BlogCutThroughTheNoiseRoute
  '/blog/defuse-with-humor': typeof BlogDefuseWithHumorRoute
  '/blog/flip-their-momentum': typeof BlogFlipTheirMomentumRoute
  '/blog/land-the-closer': typeof BlogLandTheCloserRoute
  '/blog/make-it-stick': typeof BlogMakeItStickRoute
  '/blog/read-any-room': typeof BlogReadAnyRoomRoute
  '/blog/spot-the-weakness': typeof BlogSpotTheWeaknessRoute
  '/blog/strike-emotional-chord': typeof BlogStrikeEmotionalChordRoute
  '/blog/the-crossed-quills': typeof BlogTheCrossedQuillsRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard/analysis': typeof AppAuthDashboardAnalysisRoute
  '/dashboard/debate': typeof AppAuthDashboardDebateRoute
  '/dashboard/history': typeof AppAuthDashboardHistoryRoute
  '/dashboard/opponent-profile': typeof AppAuthDashboardOpponentProfileRoute
  '/dashboard/prep': typeof AppAuthDashboardPrepRoute
  '/onboarding': typeof AppAuthOnboardingLayoutRouteWithChildren
  '/login': typeof AppLoginLayoutIndexRoute
  '/dashboard/checkout': typeof AppAuthDashboardLayoutCheckoutRoute
  '/onboarding/username': typeof AppAuthOnboardingLayoutUsernameRoute
  '/dashboard': typeof AppAuthDashboardLayoutIndexRoute
  '/dashboard/settings/billing': typeof AppAuthDashboardLayoutSettingsBillingRoute
  '/dashboard/settings': typeof AppAuthDashboardLayoutSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/_auth': typeof AppAuthRouteWithChildren
  '/blog/ask-the-killer-question': typeof BlogAskTheKillerQuestionRoute
  '/blog/back-it-up': typeof BlogBackItUpRoute
  '/blog/blueprint-part-1': typeof BlogBlueprintPart1Route
  '/blog/blueprint-part-2': typeof BlogBlueprintPart2Route
  '/blog/blueprint-part-3': typeof BlogBlueprintPart3Route
  '/blog/cut-through-the-noise': typeof BlogCutThroughTheNoiseRoute
  '/blog/defuse-with-humor': typeof BlogDefuseWithHumorRoute
  '/blog/flip-their-momentum': typeof BlogFlipTheirMomentumRoute
  '/blog/land-the-closer': typeof BlogLandTheCloserRoute
  '/blog/make-it-stick': typeof BlogMakeItStickRoute
  '/blog/read-any-room': typeof BlogReadAnyRoomRoute
  '/blog/spot-the-weakness': typeof BlogSpotTheWeaknessRoute
  '/blog/strike-emotional-chord': typeof BlogStrikeEmotionalChordRoute
  '/blog/the-crossed-quills': typeof BlogTheCrossedQuillsRoute
  '/blog/': typeof BlogIndexRoute
  '/_app/login/_layout': typeof AppLoginLayoutRouteWithChildren
  '/_app/_auth/dashboard/_layout': typeof AppAuthDashboardLayoutRouteWithChildren
  '/_app/_auth/dashboard/analysis': typeof AppAuthDashboardAnalysisRoute
  '/_app/_auth/dashboard/debate': typeof AppAuthDashboardDebateRoute
  '/_app/_auth/dashboard/history': typeof AppAuthDashboardHistoryRoute
  '/_app/_auth/dashboard/opponent-profile': typeof AppAuthDashboardOpponentProfileRoute
  '/_app/_auth/dashboard/prep': typeof AppAuthDashboardPrepRoute
  '/_app/_auth/onboarding/_layout': typeof AppAuthOnboardingLayoutRouteWithChildren
  '/_app/login/_layout/': typeof AppLoginLayoutIndexRoute
  '/_app/_auth/dashboard/_layout/checkout': typeof AppAuthDashboardLayoutCheckoutRoute
  '/_app/_auth/dashboard/_layout/settings': typeof AppAuthDashboardLayoutSettingsRouteWithChildren
  '/_app/_auth/onboarding/_layout/username': typeof AppAuthOnboardingLayoutUsernameRoute
  '/_app/_auth/dashboard/_layout/': typeof AppAuthDashboardLayoutIndexRoute
  '/_app/_auth/dashboard/_layout/settings/billing': typeof AppAuthDashboardLayoutSettingsBillingRoute
  '/_app/_auth/dashboard/_layout/settings/': typeof AppAuthDashboardLayoutSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog/ask-the-killer-question'
    | '/blog/back-it-up'
    | '/blog/blueprint-part-1'
    | '/blog/blueprint-part-2'
    | '/blog/blueprint-part-3'
    | '/blog/cut-through-the-noise'
    | '/blog/defuse-with-humor'
    | '/blog/flip-their-momentum'
    | '/blog/land-the-closer'
    | '/blog/make-it-stick'
    | '/blog/read-any-room'
    | '/blog/spot-the-weakness'
    | '/blog/strike-emotional-chord'
    | '/blog/the-crossed-quills'
    | '/blog'
    | '/login'
    | '/dashboard'
    | '/dashboard/analysis'
    | '/dashboard/debate'
    | '/dashboard/history'
    | '/dashboard/opponent-profile'
    | '/dashboard/prep'
    | '/onboarding'
    | '/login/'
    | '/dashboard/checkout'
    | '/dashboard/settings'
    | '/onboarding/username'
    | '/dashboard/'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog/ask-the-killer-question'
    | '/blog/back-it-up'
    | '/blog/blueprint-part-1'
    | '/blog/blueprint-part-2'
    | '/blog/blueprint-part-3'
    | '/blog/cut-through-the-noise'
    | '/blog/defuse-with-humor'
    | '/blog/flip-their-momentum'
    | '/blog/land-the-closer'
    | '/blog/make-it-stick'
    | '/blog/read-any-room'
    | '/blog/spot-the-weakness'
    | '/blog/strike-emotional-chord'
    | '/blog/the-crossed-quills'
    | '/blog'
    | '/dashboard/analysis'
    | '/dashboard/debate'
    | '/dashboard/history'
    | '/dashboard/opponent-profile'
    | '/dashboard/prep'
    | '/onboarding'
    | '/login'
    | '/dashboard/checkout'
    | '/onboarding/username'
    | '/dashboard'
    | '/dashboard/settings/billing'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/_auth'
    | '/blog/ask-the-killer-question'
    | '/blog/back-it-up'
    | '/blog/blueprint-part-1'
    | '/blog/blueprint-part-2'
    | '/blog/blueprint-part-3'
    | '/blog/cut-through-the-noise'
    | '/blog/defuse-with-humor'
    | '/blog/flip-their-momentum'
    | '/blog/land-the-closer'
    | '/blog/make-it-stick'
    | '/blog/read-any-room'
    | '/blog/spot-the-weakness'
    | '/blog/strike-emotional-chord'
    | '/blog/the-crossed-quills'
    | '/blog/'
    | '/_app/login/_layout'
    | '/_app/_auth/dashboard/_layout'
    | '/_app/_auth/dashboard/analysis'
    | '/_app/_auth/dashboard/debate'
    | '/_app/_auth/dashboard/history'
    | '/_app/_auth/dashboard/opponent-profile'
    | '/_app/_auth/dashboard/prep'
    | '/_app/_auth/onboarding/_layout'
    | '/_app/login/_layout/'
    | '/_app/_auth/dashboard/_layout/checkout'
    | '/_app/_auth/dashboard/_layout/settings'
    | '/_app/_auth/onboarding/_layout/username'
    | '/_app/_auth/dashboard/_layout/'
    | '/_app/_auth/dashboard/_layout/settings/billing'
    | '/_app/_auth/dashboard/_layout/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BlogAskTheKillerQuestionRoute: typeof BlogAskTheKillerQuestionRoute
  BlogBackItUpRoute: typeof BlogBackItUpRoute
  BlogBlueprintPart1Route: typeof BlogBlueprintPart1Route
  BlogBlueprintPart2Route: typeof BlogBlueprintPart2Route
  BlogBlueprintPart3Route: typeof BlogBlueprintPart3Route
  BlogCutThroughTheNoiseRoute: typeof BlogCutThroughTheNoiseRoute
  BlogDefuseWithHumorRoute: typeof BlogDefuseWithHumorRoute
  BlogFlipTheirMomentumRoute: typeof BlogFlipTheirMomentumRoute
  BlogLandTheCloserRoute: typeof BlogLandTheCloserRoute
  BlogMakeItStickRoute: typeof BlogMakeItStickRoute
  BlogReadAnyRoomRoute: typeof BlogReadAnyRoomRoute
  BlogSpotTheWeaknessRoute: typeof BlogSpotTheWeaknessRoute
  BlogStrikeEmotionalChordRoute: typeof BlogStrikeEmotionalChordRoute
  BlogTheCrossedQuillsRoute: typeof BlogTheCrossedQuillsRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/the-crossed-quills': {
      id: '/blog/the-crossed-quills'
      path: '/blog/the-crossed-quills'
      fullPath: '/blog/the-crossed-quills'
      preLoaderRoute: typeof BlogTheCrossedQuillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/strike-emotional-chord': {
      id: '/blog/strike-emotional-chord'
      path: '/blog/strike-emotional-chord'
      fullPath: '/blog/strike-emotional-chord'
      preLoaderRoute: typeof BlogStrikeEmotionalChordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/spot-the-weakness': {
      id: '/blog/spot-the-weakness'
      path: '/blog/spot-the-weakness'
      fullPath: '/blog/spot-the-weakness'
      preLoaderRoute: typeof BlogSpotTheWeaknessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/read-any-room': {
      id: '/blog/read-any-room'
      path: '/blog/read-any-room'
      fullPath: '/blog/read-any-room'
      preLoaderRoute: typeof BlogReadAnyRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/make-it-stick': {
      id: '/blog/make-it-stick'
      path: '/blog/make-it-stick'
      fullPath: '/blog/make-it-stick'
      preLoaderRoute: typeof BlogMakeItStickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/land-the-closer': {
      id: '/blog/land-the-closer'
      path: '/blog/land-the-closer'
      fullPath: '/blog/land-the-closer'
      preLoaderRoute: typeof BlogLandTheCloserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/flip-their-momentum': {
      id: '/blog/flip-their-momentum'
      path: '/blog/flip-their-momentum'
      fullPath: '/blog/flip-their-momentum'
      preLoaderRoute: typeof BlogFlipTheirMomentumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/defuse-with-humor': {
      id: '/blog/defuse-with-humor'
      path: '/blog/defuse-with-humor'
      fullPath: '/blog/defuse-with-humor'
      preLoaderRoute: typeof BlogDefuseWithHumorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/cut-through-the-noise': {
      id: '/blog/cut-through-the-noise'
      path: '/blog/cut-through-the-noise'
      fullPath: '/blog/cut-through-the-noise'
      preLoaderRoute: typeof BlogCutThroughTheNoiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/blueprint-part-3': {
      id: '/blog/blueprint-part-3'
      path: '/blog/blueprint-part-3'
      fullPath: '/blog/blueprint-part-3'
      preLoaderRoute: typeof BlogBlueprintPart3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/blueprint-part-2': {
      id: '/blog/blueprint-part-2'
      path: '/blog/blueprint-part-2'
      fullPath: '/blog/blueprint-part-2'
      preLoaderRoute: typeof BlogBlueprintPart2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/blueprint-part-1': {
      id: '/blog/blueprint-part-1'
      path: '/blog/blueprint-part-1'
      fullPath: '/blog/blueprint-part-1'
      preLoaderRoute: typeof BlogBlueprintPart1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/back-it-up': {
      id: '/blog/back-it-up'
      path: '/blog/back-it-up'
      fullPath: '/blog/back-it-up'
      preLoaderRoute: typeof BlogBackItUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/ask-the-killer-question': {
      id: '/blog/ask-the-killer-question'
      path: '/blog/ask-the-killer-question'
      fullPath: '/blog/ask-the-killer-question'
      preLoaderRoute: typeof BlogAskTheKillerQuestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_auth': {
      id: '/_app/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppAuthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login/_layout': {
      id: '/_app/login/_layout'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginLayoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login/_layout/': {
      id: '/_app/login/_layout/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof AppLoginLayoutIndexRouteImport
      parentRoute: typeof AppLoginLayoutRoute
    }
    '/_app/_auth/onboarding/_layout': {
      id: '/_app/_auth/onboarding/_layout'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppAuthOnboardingLayoutRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/dashboard/prep': {
      id: '/_app/_auth/dashboard/prep'
      path: '/dashboard/prep'
      fullPath: '/dashboard/prep'
      preLoaderRoute: typeof AppAuthDashboardPrepRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/dashboard/opponent-profile': {
      id: '/_app/_auth/dashboard/opponent-profile'
      path: '/dashboard/opponent-profile'
      fullPath: '/dashboard/opponent-profile'
      preLoaderRoute: typeof AppAuthDashboardOpponentProfileRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/dashboard/history': {
      id: '/_app/_auth/dashboard/history'
      path: '/dashboard/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof AppAuthDashboardHistoryRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/dashboard/debate': {
      id: '/_app/_auth/dashboard/debate'
      path: '/dashboard/debate'
      fullPath: '/dashboard/debate'
      preLoaderRoute: typeof AppAuthDashboardDebateRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/dashboard/analysis': {
      id: '/_app/_auth/dashboard/analysis'
      path: '/dashboard/analysis'
      fullPath: '/dashboard/analysis'
      preLoaderRoute: typeof AppAuthDashboardAnalysisRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/dashboard/_layout': {
      id: '/_app/_auth/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppAuthDashboardLayoutRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/dashboard/_layout/': {
      id: '/_app/_auth/dashboard/_layout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppAuthDashboardLayoutIndexRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/onboarding/_layout/username': {
      id: '/_app/_auth/onboarding/_layout/username'
      path: '/username'
      fullPath: '/onboarding/username'
      preLoaderRoute: typeof AppAuthOnboardingLayoutUsernameRouteImport
      parentRoute: typeof AppAuthOnboardingLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/settings': {
      id: '/_app/_auth/dashboard/_layout/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/checkout': {
      id: '/_app/_auth/dashboard/_layout/checkout'
      path: '/checkout'
      fullPath: '/dashboard/checkout'
      preLoaderRoute: typeof AppAuthDashboardLayoutCheckoutRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/settings/': {
      id: '/_app/_auth/dashboard/_layout/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsIndexRouteImport
      parentRoute: typeof AppAuthDashboardLayoutSettingsRoute
    }
    '/_app/_auth/dashboard/_layout/settings/billing': {
      id: '/_app/_auth/dashboard/_layout/settings/billing'
      path: '/billing'
      fullPath: '/dashboard/settings/billing'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsBillingRouteImport
      parentRoute: typeof AppAuthDashboardLayoutSettingsRoute
    }
  }
}

interface AppAuthDashboardLayoutSettingsRouteChildren {
  AppAuthDashboardLayoutSettingsBillingRoute: typeof AppAuthDashboardLayoutSettingsBillingRoute
  AppAuthDashboardLayoutSettingsIndexRoute: typeof AppAuthDashboardLayoutSettingsIndexRoute
}

const AppAuthDashboardLayoutSettingsRouteChildren: AppAuthDashboardLayoutSettingsRouteChildren =
  {
    AppAuthDashboardLayoutSettingsBillingRoute:
      AppAuthDashboardLayoutSettingsBillingRoute,
    AppAuthDashboardLayoutSettingsIndexRoute:
      AppAuthDashboardLayoutSettingsIndexRoute,
  }

const AppAuthDashboardLayoutSettingsRouteWithChildren =
  AppAuthDashboardLayoutSettingsRoute._addFileChildren(
    AppAuthDashboardLayoutSettingsRouteChildren,
  )

interface AppAuthDashboardLayoutRouteChildren {
  AppAuthDashboardLayoutCheckoutRoute: typeof AppAuthDashboardLayoutCheckoutRoute
  AppAuthDashboardLayoutSettingsRoute: typeof AppAuthDashboardLayoutSettingsRouteWithChildren
  AppAuthDashboardLayoutIndexRoute: typeof AppAuthDashboardLayoutIndexRoute
}

const AppAuthDashboardLayoutRouteChildren: AppAuthDashboardLayoutRouteChildren =
  {
    AppAuthDashboardLayoutCheckoutRoute: AppAuthDashboardLayoutCheckoutRoute,
    AppAuthDashboardLayoutSettingsRoute:
      AppAuthDashboardLayoutSettingsRouteWithChildren,
    AppAuthDashboardLayoutIndexRoute: AppAuthDashboardLayoutIndexRoute,
  }

const AppAuthDashboardLayoutRouteWithChildren =
  AppAuthDashboardLayoutRoute._addFileChildren(
    AppAuthDashboardLayoutRouteChildren,
  )

interface AppAuthOnboardingLayoutRouteChildren {
  AppAuthOnboardingLayoutUsernameRoute: typeof AppAuthOnboardingLayoutUsernameRoute
}

const AppAuthOnboardingLayoutRouteChildren: AppAuthOnboardingLayoutRouteChildren =
  {
    AppAuthOnboardingLayoutUsernameRoute: AppAuthOnboardingLayoutUsernameRoute,
  }

const AppAuthOnboardingLayoutRouteWithChildren =
  AppAuthOnboardingLayoutRoute._addFileChildren(
    AppAuthOnboardingLayoutRouteChildren,
  )

interface AppAuthRouteChildren {
  AppAuthDashboardLayoutRoute: typeof AppAuthDashboardLayoutRouteWithChildren
  AppAuthDashboardAnalysisRoute: typeof AppAuthDashboardAnalysisRoute
  AppAuthDashboardDebateRoute: typeof AppAuthDashboardDebateRoute
  AppAuthDashboardHistoryRoute: typeof AppAuthDashboardHistoryRoute
  AppAuthDashboardOpponentProfileRoute: typeof AppAuthDashboardOpponentProfileRoute
  AppAuthDashboardPrepRoute: typeof AppAuthDashboardPrepRoute
  AppAuthOnboardingLayoutRoute: typeof AppAuthOnboardingLayoutRouteWithChildren
}

const AppAuthRouteChildren: AppAuthRouteChildren = {
  AppAuthDashboardLayoutRoute: AppAuthDashboardLayoutRouteWithChildren,
  AppAuthDashboardAnalysisRoute: AppAuthDashboardAnalysisRoute,
  AppAuthDashboardDebateRoute: AppAuthDashboardDebateRoute,
  AppAuthDashboardHistoryRoute: AppAuthDashboardHistoryRoute,
  AppAuthDashboardOpponentProfileRoute: AppAuthDashboardOpponentProfileRoute,
  AppAuthDashboardPrepRoute: AppAuthDashboardPrepRoute,
  AppAuthOnboardingLayoutRoute: AppAuthOnboardingLayoutRouteWithChildren,
}

const AppAuthRouteWithChildren =
  AppAuthRoute._addFileChildren(AppAuthRouteChildren)

interface AppLoginLayoutRouteChildren {
  AppLoginLayoutIndexRoute: typeof AppLoginLayoutIndexRoute
}

const AppLoginLayoutRouteChildren: AppLoginLayoutRouteChildren = {
  AppLoginLayoutIndexRoute: AppLoginLayoutIndexRoute,
}

const AppLoginLayoutRouteWithChildren = AppLoginLayoutRoute._addFileChildren(
  AppLoginLayoutRouteChildren,
)

interface AppRouteChildren {
  AppAuthRoute: typeof AppAuthRouteWithChildren
  AppLoginLayoutRoute: typeof AppLoginLayoutRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthRoute: AppAuthRouteWithChildren,
  AppLoginLayoutRoute: AppLoginLayoutRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BlogAskTheKillerQuestionRoute: BlogAskTheKillerQuestionRoute,
  BlogBackItUpRoute: BlogBackItUpRoute,
  BlogBlueprintPart1Route: BlogBlueprintPart1Route,
  BlogBlueprintPart2Route: BlogBlueprintPart2Route,
  BlogBlueprintPart3Route: BlogBlueprintPart3Route,
  BlogCutThroughTheNoiseRoute: BlogCutThroughTheNoiseRoute,
  BlogDefuseWithHumorRoute: BlogDefuseWithHumorRoute,
  BlogFlipTheirMomentumRoute: BlogFlipTheirMomentumRoute,
  BlogLandTheCloserRoute: BlogLandTheCloserRoute,
  BlogMakeItStickRoute: BlogMakeItStickRoute,
  BlogReadAnyRoomRoute: BlogReadAnyRoomRoute,
  BlogSpotTheWeaknessRoute: BlogSpotTheWeaknessRoute,
  BlogStrikeEmotionalChordRoute: BlogStrikeEmotionalChordRoute,
  BlogTheCrossedQuillsRoute: BlogTheCrossedQuillsRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
