/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WinEveryArgumentRouteImport } from './routes/win-every-argument'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as UseCasesSalesObjectionsRouteImport } from './routes/use-cases/sales-objections'
import { Route as UseCasesPresentationsRouteImport } from './routes/use-cases/presentations'
import { Route as UseCasesPoliticiansActivistsRouteImport } from './routes/use-cases/politicians-activists'
import { Route as UseCasesPitchingFundraisingRouteImport } from './routes/use-cases/pitching-fundraising'
import { Route as UseCasesParentsEducatorsRouteImport } from './routes/use-cases/parents-educators'
import { Route as UseCasesJobInterviewsRouteImport } from './routes/use-cases/job-interviews'
import { Route as UseCasesHealthcareProfessionalsRouteImport } from './routes/use-cases/healthcare-professionals'
import { Route as UseCasesDifficultConversationsRouteImport } from './routes/use-cases/difficult-conversations'
import { Route as UseCasesAttorneysLegalRouteImport } from './routes/use-cases/attorneys-legal'
import { Route as UseCasesAcademicsResearchersRouteImport } from './routes/use-cases/academics-researchers'
import { Route as BlogTheCrossedQuillsRouteImport } from './routes/blog/the-crossed-quills'
import { Route as BlogStrikeEmotionalChordRouteImport } from './routes/blog/strike-emotional-chord'
import { Route as BlogStickTheLandingRouteImport } from './routes/blog/stick-the-landing'
import { Route as BlogSpotTheWeaknessRouteImport } from './routes/blog/spot-the-weakness'
import { Route as BlogScenarioTreatmentRefusalRouteImport } from './routes/blog/scenario-treatment-refusal'
import { Route as BlogScenarioEarlyCustomerSalesRouteImport } from './routes/blog/scenario-early-customer-sales'
import { Route as BlogScenarioCustomerDiscoveryRouteImport } from './routes/blog/scenario-customer-discovery'
import { Route as BlogScenarioContractNegotiationRouteImport } from './routes/blog/scenario-contract-negotiation'
import { Route as BlogReadAnyRoomRouteImport } from './routes/blog/read-any-room'
import { Route as BlogOwnYourWeaknessesRouteImport } from './routes/blog/own-your-weaknesses'
import { Route as BlogMakeItStickRouteImport } from './routes/blog/make-it-stick'
import { Route as BlogLandTheCloserRouteImport } from './routes/blog/land-the-closer'
import { Route as BlogFlipTheirMomentumRouteImport } from './routes/blog/flip-their-momentum'
import { Route as BlogDefuseWithHumorRouteImport } from './routes/blog/defuse-with-humor'
import { Route as BlogCutThroughTheNoiseRouteImport } from './routes/blog/cut-through-the-noise'
import { Route as BlogBlueprintPart3RouteImport } from './routes/blog/blueprint-part-3'
import { Route as BlogBlueprintPart2RouteImport } from './routes/blog/blueprint-part-2'
import { Route as BlogBlueprintPart1RouteImport } from './routes/blog/blueprint-part-1'
import { Route as BlogBackItUpRouteImport } from './routes/blog/back-it-up'
import { Route as BlogAskTheKillerQuestionRouteImport } from './routes/blog/ask-the-killer-question'
import { Route as AppAuthRouteImport } from './routes/_app/_auth'
import { Route as AppLoginLayoutRouteImport } from './routes/_app/login/_layout'
import { Route as AppClaimTokenRouteImport } from './routes/_app/claim.$token'
import { Route as AppLoginLayoutIndexRouteImport } from './routes/_app/login/_layout.index'
import { Route as AppAuthOnboardingLayoutRouteImport } from './routes/_app/_auth/onboarding/_layout'
import { Route as AppAuthDashboardPrepRouteImport } from './routes/_app/_auth/dashboard/prep'
import { Route as AppAuthDashboardOpponentProfileRouteImport } from './routes/_app/_auth/dashboard/opponent-profile'
import { Route as AppAuthDashboardHistoryRouteImport } from './routes/_app/_auth/dashboard/history'
import { Route as AppAuthDashboardDebateRouteImport } from './routes/_app/_auth/dashboard/debate'
import { Route as AppAuthDashboardAnalysisRouteImport } from './routes/_app/_auth/dashboard/analysis'
import { Route as AppAuthDashboardLayoutRouteImport } from './routes/_app/_auth/dashboard/_layout'
import { Route as AppAuthDashboardLayoutIndexRouteImport } from './routes/_app/_auth/dashboard/_layout.index'
import { Route as AppAuthOnboardingLayoutUsernameRouteImport } from './routes/_app/_auth/onboarding/_layout.username'
import { Route as AppAuthDashboardLayoutSettingsRouteImport } from './routes/_app/_auth/dashboard/_layout.settings'
import { Route as AppAuthDashboardLayoutAdminRouteImport } from './routes/_app/_auth/dashboard/_layout.admin'
import { Route as AppAuthDashboardLayoutSettingsIndexRouteImport } from './routes/_app/_auth/dashboard/_layout.settings.index'
import { Route as AppAuthDashboardLayoutSettingsResearchRouteImport } from './routes/_app/_auth/dashboard/_layout.settings.research'
import { Route as AppAuthDashboardLayoutSettingsBillingRouteImport } from './routes/_app/_auth/dashboard/_layout.settings.billing'

const WinEveryArgumentRoute = WinEveryArgumentRouteImport.update({
  id: '/win-every-argument',
  path: '/win-every-argument',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesSalesObjectionsRoute = UseCasesSalesObjectionsRouteImport.update({
  id: '/use-cases/sales-objections',
  path: '/use-cases/sales-objections',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesPresentationsRoute = UseCasesPresentationsRouteImport.update({
  id: '/use-cases/presentations',
  path: '/use-cases/presentations',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesPoliticiansActivistsRoute =
  UseCasesPoliticiansActivistsRouteImport.update({
    id: '/use-cases/politicians-activists',
    path: '/use-cases/politicians-activists',
    getParentRoute: () => rootRouteImport,
  } as any)
const UseCasesPitchingFundraisingRoute =
  UseCasesPitchingFundraisingRouteImport.update({
    id: '/use-cases/pitching-fundraising',
    path: '/use-cases/pitching-fundraising',
    getParentRoute: () => rootRouteImport,
  } as any)
const UseCasesParentsEducatorsRoute =
  UseCasesParentsEducatorsRouteImport.update({
    id: '/use-cases/parents-educators',
    path: '/use-cases/parents-educators',
    getParentRoute: () => rootRouteImport,
  } as any)
const UseCasesJobInterviewsRoute = UseCasesJobInterviewsRouteImport.update({
  id: '/use-cases/job-interviews',
  path: '/use-cases/job-interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesHealthcareProfessionalsRoute =
  UseCasesHealthcareProfessionalsRouteImport.update({
    id: '/use-cases/healthcare-professionals',
    path: '/use-cases/healthcare-professionals',
    getParentRoute: () => rootRouteImport,
  } as any)
const UseCasesDifficultConversationsRoute =
  UseCasesDifficultConversationsRouteImport.update({
    id: '/use-cases/difficult-conversations',
    path: '/use-cases/difficult-conversations',
    getParentRoute: () => rootRouteImport,
  } as any)
const UseCasesAttorneysLegalRoute = UseCasesAttorneysLegalRouteImport.update({
  id: '/use-cases/attorneys-legal',
  path: '/use-cases/attorneys-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesAcademicsResearchersRoute =
  UseCasesAcademicsResearchersRouteImport.update({
    id: '/use-cases/academics-researchers',
    path: '/use-cases/academics-researchers',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogTheCrossedQuillsRoute = BlogTheCrossedQuillsRouteImport.update({
  id: '/blog/the-crossed-quills',
  path: '/blog/the-crossed-quills',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogStrikeEmotionalChordRoute =
  BlogStrikeEmotionalChordRouteImport.update({
    id: '/blog/strike-emotional-chord',
    path: '/blog/strike-emotional-chord',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogStickTheLandingRoute = BlogStickTheLandingRouteImport.update({
  id: '/blog/stick-the-landing',
  path: '/blog/stick-the-landing',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSpotTheWeaknessRoute = BlogSpotTheWeaknessRouteImport.update({
  id: '/blog/spot-the-weakness',
  path: '/blog/spot-the-weakness',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogScenarioTreatmentRefusalRoute =
  BlogScenarioTreatmentRefusalRouteImport.update({
    id: '/blog/scenario-treatment-refusal',
    path: '/blog/scenario-treatment-refusal',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogScenarioEarlyCustomerSalesRoute =
  BlogScenarioEarlyCustomerSalesRouteImport.update({
    id: '/blog/scenario-early-customer-sales',
    path: '/blog/scenario-early-customer-sales',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogScenarioCustomerDiscoveryRoute =
  BlogScenarioCustomerDiscoveryRouteImport.update({
    id: '/blog/scenario-customer-discovery',
    path: '/blog/scenario-customer-discovery',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogScenarioContractNegotiationRoute =
  BlogScenarioContractNegotiationRouteImport.update({
    id: '/blog/scenario-contract-negotiation',
    path: '/blog/scenario-contract-negotiation',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogReadAnyRoomRoute = BlogReadAnyRoomRouteImport.update({
  id: '/blog/read-any-room',
  path: '/blog/read-any-room',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogOwnYourWeaknessesRoute = BlogOwnYourWeaknessesRouteImport.update({
  id: '/blog/own-your-weaknesses',
  path: '/blog/own-your-weaknesses',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogMakeItStickRoute = BlogMakeItStickRouteImport.update({
  id: '/blog/make-it-stick',
  path: '/blog/make-it-stick',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogLandTheCloserRoute = BlogLandTheCloserRouteImport.update({
  id: '/blog/land-the-closer',
  path: '/blog/land-the-closer',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogFlipTheirMomentumRoute = BlogFlipTheirMomentumRouteImport.update({
  id: '/blog/flip-their-momentum',
  path: '/blog/flip-their-momentum',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogDefuseWithHumorRoute = BlogDefuseWithHumorRouteImport.update({
  id: '/blog/defuse-with-humor',
  path: '/blog/defuse-with-humor',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCutThroughTheNoiseRoute = BlogCutThroughTheNoiseRouteImport.update({
  id: '/blog/cut-through-the-noise',
  path: '/blog/cut-through-the-noise',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogBlueprintPart3Route = BlogBlueprintPart3RouteImport.update({
  id: '/blog/blueprint-part-3',
  path: '/blog/blueprint-part-3',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogBlueprintPart2Route = BlogBlueprintPart2RouteImport.update({
  id: '/blog/blueprint-part-2',
  path: '/blog/blueprint-part-2',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogBlueprintPart1Route = BlogBlueprintPart1RouteImport.update({
  id: '/blog/blueprint-part-1',
  path: '/blog/blueprint-part-1',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogBackItUpRoute = BlogBackItUpRouteImport.update({
  id: '/blog/back-it-up',
  path: '/blog/back-it-up',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAskTheKillerQuestionRoute =
  BlogAskTheKillerQuestionRouteImport.update({
    id: '/blog/ask-the-killer-question',
    path: '/blog/ask-the-killer-question',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppAuthRoute = AppAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginLayoutRoute = AppLoginLayoutRouteImport.update({
  id: '/login/_layout',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppClaimTokenRoute = AppClaimTokenRouteImport.update({
  id: '/claim/$token',
  path: '/claim/$token',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginLayoutIndexRoute = AppLoginLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLoginLayoutRoute,
} as any)
const AppAuthOnboardingLayoutRoute = AppAuthOnboardingLayoutRouteImport.update({
  id: '/onboarding/_layout',
  path: '/onboarding',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthDashboardPrepRoute = AppAuthDashboardPrepRouteImport.update({
  id: '/dashboard/prep',
  path: '/dashboard/prep',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthDashboardOpponentProfileRoute =
  AppAuthDashboardOpponentProfileRouteImport.update({
    id: '/dashboard/opponent-profile',
    path: '/dashboard/opponent-profile',
    getParentRoute: () => AppAuthRoute,
  } as any)
const AppAuthDashboardHistoryRoute = AppAuthDashboardHistoryRouteImport.update({
  id: '/dashboard/history',
  path: '/dashboard/history',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthDashboardDebateRoute = AppAuthDashboardDebateRouteImport.update({
  id: '/dashboard/debate',
  path: '/dashboard/debate',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthDashboardAnalysisRoute =
  AppAuthDashboardAnalysisRouteImport.update({
    id: '/dashboard/analysis',
    path: '/dashboard/analysis',
    getParentRoute: () => AppAuthRoute,
  } as any)
const AppAuthDashboardLayoutRoute = AppAuthDashboardLayoutRouteImport.update({
  id: '/dashboard/_layout',
  path: '/dashboard',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthDashboardLayoutIndexRoute =
  AppAuthDashboardLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthOnboardingLayoutUsernameRoute =
  AppAuthOnboardingLayoutUsernameRouteImport.update({
    id: '/username',
    path: '/username',
    getParentRoute: () => AppAuthOnboardingLayoutRoute,
  } as any)
const AppAuthDashboardLayoutSettingsRoute =
  AppAuthDashboardLayoutSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthDashboardLayoutAdminRoute =
  AppAuthDashboardLayoutAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthDashboardLayoutSettingsIndexRoute =
  AppAuthDashboardLayoutSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAuthDashboardLayoutSettingsRoute,
  } as any)
const AppAuthDashboardLayoutSettingsResearchRoute =
  AppAuthDashboardLayoutSettingsResearchRouteImport.update({
    id: '/research',
    path: '/research',
    getParentRoute: () => AppAuthDashboardLayoutSettingsRoute,
  } as any)
const AppAuthDashboardLayoutSettingsBillingRoute =
  AppAuthDashboardLayoutSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AppAuthDashboardLayoutSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/win-every-argument': typeof WinEveryArgumentRoute
  '/blog/ask-the-killer-question': typeof BlogAskTheKillerQuestionRoute
  '/blog/back-it-up': typeof BlogBackItUpRoute
  '/blog/blueprint-part-1': typeof BlogBlueprintPart1Route
  '/blog/blueprint-part-2': typeof BlogBlueprintPart2Route
  '/blog/blueprint-part-3': typeof BlogBlueprintPart3Route
  '/blog/cut-through-the-noise': typeof BlogCutThroughTheNoiseRoute
  '/blog/defuse-with-humor': typeof BlogDefuseWithHumorRoute
  '/blog/flip-their-momentum': typeof BlogFlipTheirMomentumRoute
  '/blog/land-the-closer': typeof BlogLandTheCloserRoute
  '/blog/make-it-stick': typeof BlogMakeItStickRoute
  '/blog/own-your-weaknesses': typeof BlogOwnYourWeaknessesRoute
  '/blog/read-any-room': typeof BlogReadAnyRoomRoute
  '/blog/scenario-contract-negotiation': typeof BlogScenarioContractNegotiationRoute
  '/blog/scenario-customer-discovery': typeof BlogScenarioCustomerDiscoveryRoute
  '/blog/scenario-early-customer-sales': typeof BlogScenarioEarlyCustomerSalesRoute
  '/blog/scenario-treatment-refusal': typeof BlogScenarioTreatmentRefusalRoute
  '/blog/spot-the-weakness': typeof BlogSpotTheWeaknessRoute
  '/blog/stick-the-landing': typeof BlogStickTheLandingRoute
  '/blog/strike-emotional-chord': typeof BlogStrikeEmotionalChordRoute
  '/blog/the-crossed-quills': typeof BlogTheCrossedQuillsRoute
  '/use-cases/academics-researchers': typeof UseCasesAcademicsResearchersRoute
  '/use-cases/attorneys-legal': typeof UseCasesAttorneysLegalRoute
  '/use-cases/difficult-conversations': typeof UseCasesDifficultConversationsRoute
  '/use-cases/healthcare-professionals': typeof UseCasesHealthcareProfessionalsRoute
  '/use-cases/job-interviews': typeof UseCasesJobInterviewsRoute
  '/use-cases/parents-educators': typeof UseCasesParentsEducatorsRoute
  '/use-cases/pitching-fundraising': typeof UseCasesPitchingFundraisingRoute
  '/use-cases/politicians-activists': typeof UseCasesPoliticiansActivistsRoute
  '/use-cases/presentations': typeof UseCasesPresentationsRoute
  '/use-cases/sales-objections': typeof UseCasesSalesObjectionsRoute
  '/blog': typeof BlogIndexRoute
  '/claim/$token': typeof AppClaimTokenRoute
  '/login': typeof AppLoginLayoutRouteWithChildren
  '/dashboard': typeof AppAuthDashboardLayoutRouteWithChildren
  '/dashboard/analysis': typeof AppAuthDashboardAnalysisRoute
  '/dashboard/debate': typeof AppAuthDashboardDebateRoute
  '/dashboard/history': typeof AppAuthDashboardHistoryRoute
  '/dashboard/opponent-profile': typeof AppAuthDashboardOpponentProfileRoute
  '/dashboard/prep': typeof AppAuthDashboardPrepRoute
  '/onboarding': typeof AppAuthOnboardingLayoutRouteWithChildren
  '/login/': typeof AppLoginLayoutIndexRoute
  '/dashboard/admin': typeof AppAuthDashboardLayoutAdminRoute
  '/dashboard/settings': typeof AppAuthDashboardLayoutSettingsRouteWithChildren
  '/onboarding/username': typeof AppAuthOnboardingLayoutUsernameRoute
  '/dashboard/': typeof AppAuthDashboardLayoutIndexRoute
  '/dashboard/settings/billing': typeof AppAuthDashboardLayoutSettingsBillingRoute
  '/dashboard/settings/research': typeof AppAuthDashboardLayoutSettingsResearchRoute
  '/dashboard/settings/': typeof AppAuthDashboardLayoutSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/win-every-argument': typeof WinEveryArgumentRoute
  '/blog/ask-the-killer-question': typeof BlogAskTheKillerQuestionRoute
  '/blog/back-it-up': typeof BlogBackItUpRoute
  '/blog/blueprint-part-1': typeof BlogBlueprintPart1Route
  '/blog/blueprint-part-2': typeof BlogBlueprintPart2Route
  '/blog/blueprint-part-3': typeof BlogBlueprintPart3Route
  '/blog/cut-through-the-noise': typeof BlogCutThroughTheNoiseRoute
  '/blog/defuse-with-humor': typeof BlogDefuseWithHumorRoute
  '/blog/flip-their-momentum': typeof BlogFlipTheirMomentumRoute
  '/blog/land-the-closer': typeof BlogLandTheCloserRoute
  '/blog/make-it-stick': typeof BlogMakeItStickRoute
  '/blog/own-your-weaknesses': typeof BlogOwnYourWeaknessesRoute
  '/blog/read-any-room': typeof BlogReadAnyRoomRoute
  '/blog/scenario-contract-negotiation': typeof BlogScenarioContractNegotiationRoute
  '/blog/scenario-customer-discovery': typeof BlogScenarioCustomerDiscoveryRoute
  '/blog/scenario-early-customer-sales': typeof BlogScenarioEarlyCustomerSalesRoute
  '/blog/scenario-treatment-refusal': typeof BlogScenarioTreatmentRefusalRoute
  '/blog/spot-the-weakness': typeof BlogSpotTheWeaknessRoute
  '/blog/stick-the-landing': typeof BlogStickTheLandingRoute
  '/blog/strike-emotional-chord': typeof BlogStrikeEmotionalChordRoute
  '/blog/the-crossed-quills': typeof BlogTheCrossedQuillsRoute
  '/use-cases/academics-researchers': typeof UseCasesAcademicsResearchersRoute
  '/use-cases/attorneys-legal': typeof UseCasesAttorneysLegalRoute
  '/use-cases/difficult-conversations': typeof UseCasesDifficultConversationsRoute
  '/use-cases/healthcare-professionals': typeof UseCasesHealthcareProfessionalsRoute
  '/use-cases/job-interviews': typeof UseCasesJobInterviewsRoute
  '/use-cases/parents-educators': typeof UseCasesParentsEducatorsRoute
  '/use-cases/pitching-fundraising': typeof UseCasesPitchingFundraisingRoute
  '/use-cases/politicians-activists': typeof UseCasesPoliticiansActivistsRoute
  '/use-cases/presentations': typeof UseCasesPresentationsRoute
  '/use-cases/sales-objections': typeof UseCasesSalesObjectionsRoute
  '/blog': typeof BlogIndexRoute
  '/claim/$token': typeof AppClaimTokenRoute
  '/dashboard/analysis': typeof AppAuthDashboardAnalysisRoute
  '/dashboard/debate': typeof AppAuthDashboardDebateRoute
  '/dashboard/history': typeof AppAuthDashboardHistoryRoute
  '/dashboard/opponent-profile': typeof AppAuthDashboardOpponentProfileRoute
  '/dashboard/prep': typeof AppAuthDashboardPrepRoute
  '/onboarding': typeof AppAuthOnboardingLayoutRouteWithChildren
  '/login': typeof AppLoginLayoutIndexRoute
  '/dashboard/admin': typeof AppAuthDashboardLayoutAdminRoute
  '/onboarding/username': typeof AppAuthOnboardingLayoutUsernameRoute
  '/dashboard': typeof AppAuthDashboardLayoutIndexRoute
  '/dashboard/settings/billing': typeof AppAuthDashboardLayoutSettingsBillingRoute
  '/dashboard/settings/research': typeof AppAuthDashboardLayoutSettingsResearchRoute
  '/dashboard/settings': typeof AppAuthDashboardLayoutSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/win-every-argument': typeof WinEveryArgumentRoute
  '/_app/_auth': typeof AppAuthRouteWithChildren
  '/blog/ask-the-killer-question': typeof BlogAskTheKillerQuestionRoute
  '/blog/back-it-up': typeof BlogBackItUpRoute
  '/blog/blueprint-part-1': typeof BlogBlueprintPart1Route
  '/blog/blueprint-part-2': typeof BlogBlueprintPart2Route
  '/blog/blueprint-part-3': typeof BlogBlueprintPart3Route
  '/blog/cut-through-the-noise': typeof BlogCutThroughTheNoiseRoute
  '/blog/defuse-with-humor': typeof BlogDefuseWithHumorRoute
  '/blog/flip-their-momentum': typeof BlogFlipTheirMomentumRoute
  '/blog/land-the-closer': typeof BlogLandTheCloserRoute
  '/blog/make-it-stick': typeof BlogMakeItStickRoute
  '/blog/own-your-weaknesses': typeof BlogOwnYourWeaknessesRoute
  '/blog/read-any-room': typeof BlogReadAnyRoomRoute
  '/blog/scenario-contract-negotiation': typeof BlogScenarioContractNegotiationRoute
  '/blog/scenario-customer-discovery': typeof BlogScenarioCustomerDiscoveryRoute
  '/blog/scenario-early-customer-sales': typeof BlogScenarioEarlyCustomerSalesRoute
  '/blog/scenario-treatment-refusal': typeof BlogScenarioTreatmentRefusalRoute
  '/blog/spot-the-weakness': typeof BlogSpotTheWeaknessRoute
  '/blog/stick-the-landing': typeof BlogStickTheLandingRoute
  '/blog/strike-emotional-chord': typeof BlogStrikeEmotionalChordRoute
  '/blog/the-crossed-quills': typeof BlogTheCrossedQuillsRoute
  '/use-cases/academics-researchers': typeof UseCasesAcademicsResearchersRoute
  '/use-cases/attorneys-legal': typeof UseCasesAttorneysLegalRoute
  '/use-cases/difficult-conversations': typeof UseCasesDifficultConversationsRoute
  '/use-cases/healthcare-professionals': typeof UseCasesHealthcareProfessionalsRoute
  '/use-cases/job-interviews': typeof UseCasesJobInterviewsRoute
  '/use-cases/parents-educators': typeof UseCasesParentsEducatorsRoute
  '/use-cases/pitching-fundraising': typeof UseCasesPitchingFundraisingRoute
  '/use-cases/politicians-activists': typeof UseCasesPoliticiansActivistsRoute
  '/use-cases/presentations': typeof UseCasesPresentationsRoute
  '/use-cases/sales-objections': typeof UseCasesSalesObjectionsRoute
  '/blog/': typeof BlogIndexRoute
  '/_app/claim/$token': typeof AppClaimTokenRoute
  '/_app/login/_layout': typeof AppLoginLayoutRouteWithChildren
  '/_app/_auth/dashboard/_layout': typeof AppAuthDashboardLayoutRouteWithChildren
  '/_app/_auth/dashboard/analysis': typeof AppAuthDashboardAnalysisRoute
  '/_app/_auth/dashboard/debate': typeof AppAuthDashboardDebateRoute
  '/_app/_auth/dashboard/history': typeof AppAuthDashboardHistoryRoute
  '/_app/_auth/dashboard/opponent-profile': typeof AppAuthDashboardOpponentProfileRoute
  '/_app/_auth/dashboard/prep': typeof AppAuthDashboardPrepRoute
  '/_app/_auth/onboarding/_layout': typeof AppAuthOnboardingLayoutRouteWithChildren
  '/_app/login/_layout/': typeof AppLoginLayoutIndexRoute
  '/_app/_auth/dashboard/_layout/admin': typeof AppAuthDashboardLayoutAdminRoute
  '/_app/_auth/dashboard/_layout/settings': typeof AppAuthDashboardLayoutSettingsRouteWithChildren
  '/_app/_auth/onboarding/_layout/username': typeof AppAuthOnboardingLayoutUsernameRoute
  '/_app/_auth/dashboard/_layout/': typeof AppAuthDashboardLayoutIndexRoute
  '/_app/_auth/dashboard/_layout/settings/billing': typeof AppAuthDashboardLayoutSettingsBillingRoute
  '/_app/_auth/dashboard/_layout/settings/research': typeof AppAuthDashboardLayoutSettingsResearchRoute
  '/_app/_auth/dashboard/_layout/settings/': typeof AppAuthDashboardLayoutSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/win-every-argument'
    | '/blog/ask-the-killer-question'
    | '/blog/back-it-up'
    | '/blog/blueprint-part-1'
    | '/blog/blueprint-part-2'
    | '/blog/blueprint-part-3'
    | '/blog/cut-through-the-noise'
    | '/blog/defuse-with-humor'
    | '/blog/flip-their-momentum'
    | '/blog/land-the-closer'
    | '/blog/make-it-stick'
    | '/blog/own-your-weaknesses'
    | '/blog/read-any-room'
    | '/blog/scenario-contract-negotiation'
    | '/blog/scenario-customer-discovery'
    | '/blog/scenario-early-customer-sales'
    | '/blog/scenario-treatment-refusal'
    | '/blog/spot-the-weakness'
    | '/blog/stick-the-landing'
    | '/blog/strike-emotional-chord'
    | '/blog/the-crossed-quills'
    | '/use-cases/academics-researchers'
    | '/use-cases/attorneys-legal'
    | '/use-cases/difficult-conversations'
    | '/use-cases/healthcare-professionals'
    | '/use-cases/job-interviews'
    | '/use-cases/parents-educators'
    | '/use-cases/pitching-fundraising'
    | '/use-cases/politicians-activists'
    | '/use-cases/presentations'
    | '/use-cases/sales-objections'
    | '/blog'
    | '/claim/$token'
    | '/login'
    | '/dashboard'
    | '/dashboard/analysis'
    | '/dashboard/debate'
    | '/dashboard/history'
    | '/dashboard/opponent-profile'
    | '/dashboard/prep'
    | '/onboarding'
    | '/login/'
    | '/dashboard/admin'
    | '/dashboard/settings'
    | '/onboarding/username'
    | '/dashboard/'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/research'
    | '/dashboard/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/win-every-argument'
    | '/blog/ask-the-killer-question'
    | '/blog/back-it-up'
    | '/blog/blueprint-part-1'
    | '/blog/blueprint-part-2'
    | '/blog/blueprint-part-3'
    | '/blog/cut-through-the-noise'
    | '/blog/defuse-with-humor'
    | '/blog/flip-their-momentum'
    | '/blog/land-the-closer'
    | '/blog/make-it-stick'
    | '/blog/own-your-weaknesses'
    | '/blog/read-any-room'
    | '/blog/scenario-contract-negotiation'
    | '/blog/scenario-customer-discovery'
    | '/blog/scenario-early-customer-sales'
    | '/blog/scenario-treatment-refusal'
    | '/blog/spot-the-weakness'
    | '/blog/stick-the-landing'
    | '/blog/strike-emotional-chord'
    | '/blog/the-crossed-quills'
    | '/use-cases/academics-researchers'
    | '/use-cases/attorneys-legal'
    | '/use-cases/difficult-conversations'
    | '/use-cases/healthcare-professionals'
    | '/use-cases/job-interviews'
    | '/use-cases/parents-educators'
    | '/use-cases/pitching-fundraising'
    | '/use-cases/politicians-activists'
    | '/use-cases/presentations'
    | '/use-cases/sales-objections'
    | '/blog'
    | '/claim/$token'
    | '/dashboard/analysis'
    | '/dashboard/debate'
    | '/dashboard/history'
    | '/dashboard/opponent-profile'
    | '/dashboard/prep'
    | '/onboarding'
    | '/login'
    | '/dashboard/admin'
    | '/onboarding/username'
    | '/dashboard'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/research'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/contact'
    | '/win-every-argument'
    | '/_app/_auth'
    | '/blog/ask-the-killer-question'
    | '/blog/back-it-up'
    | '/blog/blueprint-part-1'
    | '/blog/blueprint-part-2'
    | '/blog/blueprint-part-3'
    | '/blog/cut-through-the-noise'
    | '/blog/defuse-with-humor'
    | '/blog/flip-their-momentum'
    | '/blog/land-the-closer'
    | '/blog/make-it-stick'
    | '/blog/own-your-weaknesses'
    | '/blog/read-any-room'
    | '/blog/scenario-contract-negotiation'
    | '/blog/scenario-customer-discovery'
    | '/blog/scenario-early-customer-sales'
    | '/blog/scenario-treatment-refusal'
    | '/blog/spot-the-weakness'
    | '/blog/stick-the-landing'
    | '/blog/strike-emotional-chord'
    | '/blog/the-crossed-quills'
    | '/use-cases/academics-researchers'
    | '/use-cases/attorneys-legal'
    | '/use-cases/difficult-conversations'
    | '/use-cases/healthcare-professionals'
    | '/use-cases/job-interviews'
    | '/use-cases/parents-educators'
    | '/use-cases/pitching-fundraising'
    | '/use-cases/politicians-activists'
    | '/use-cases/presentations'
    | '/use-cases/sales-objections'
    | '/blog/'
    | '/_app/claim/$token'
    | '/_app/login/_layout'
    | '/_app/_auth/dashboard/_layout'
    | '/_app/_auth/dashboard/analysis'
    | '/_app/_auth/dashboard/debate'
    | '/_app/_auth/dashboard/history'
    | '/_app/_auth/dashboard/opponent-profile'
    | '/_app/_auth/dashboard/prep'
    | '/_app/_auth/onboarding/_layout'
    | '/_app/login/_layout/'
    | '/_app/_auth/dashboard/_layout/admin'
    | '/_app/_auth/dashboard/_layout/settings'
    | '/_app/_auth/onboarding/_layout/username'
    | '/_app/_auth/dashboard/_layout/'
    | '/_app/_auth/dashboard/_layout/settings/billing'
    | '/_app/_auth/dashboard/_layout/settings/research'
    | '/_app/_auth/dashboard/_layout/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  WinEveryArgumentRoute: typeof WinEveryArgumentRoute
  BlogAskTheKillerQuestionRoute: typeof BlogAskTheKillerQuestionRoute
  BlogBackItUpRoute: typeof BlogBackItUpRoute
  BlogBlueprintPart1Route: typeof BlogBlueprintPart1Route
  BlogBlueprintPart2Route: typeof BlogBlueprintPart2Route
  BlogBlueprintPart3Route: typeof BlogBlueprintPart3Route
  BlogCutThroughTheNoiseRoute: typeof BlogCutThroughTheNoiseRoute
  BlogDefuseWithHumorRoute: typeof BlogDefuseWithHumorRoute
  BlogFlipTheirMomentumRoute: typeof BlogFlipTheirMomentumRoute
  BlogLandTheCloserRoute: typeof BlogLandTheCloserRoute
  BlogMakeItStickRoute: typeof BlogMakeItStickRoute
  BlogOwnYourWeaknessesRoute: typeof BlogOwnYourWeaknessesRoute
  BlogReadAnyRoomRoute: typeof BlogReadAnyRoomRoute
  BlogScenarioContractNegotiationRoute: typeof BlogScenarioContractNegotiationRoute
  BlogScenarioCustomerDiscoveryRoute: typeof BlogScenarioCustomerDiscoveryRoute
  BlogScenarioEarlyCustomerSalesRoute: typeof BlogScenarioEarlyCustomerSalesRoute
  BlogScenarioTreatmentRefusalRoute: typeof BlogScenarioTreatmentRefusalRoute
  BlogSpotTheWeaknessRoute: typeof BlogSpotTheWeaknessRoute
  BlogStickTheLandingRoute: typeof BlogStickTheLandingRoute
  BlogStrikeEmotionalChordRoute: typeof BlogStrikeEmotionalChordRoute
  BlogTheCrossedQuillsRoute: typeof BlogTheCrossedQuillsRoute
  UseCasesAcademicsResearchersRoute: typeof UseCasesAcademicsResearchersRoute
  UseCasesAttorneysLegalRoute: typeof UseCasesAttorneysLegalRoute
  UseCasesDifficultConversationsRoute: typeof UseCasesDifficultConversationsRoute
  UseCasesHealthcareProfessionalsRoute: typeof UseCasesHealthcareProfessionalsRoute
  UseCasesJobInterviewsRoute: typeof UseCasesJobInterviewsRoute
  UseCasesParentsEducatorsRoute: typeof UseCasesParentsEducatorsRoute
  UseCasesPitchingFundraisingRoute: typeof UseCasesPitchingFundraisingRoute
  UseCasesPoliticiansActivistsRoute: typeof UseCasesPoliticiansActivistsRoute
  UseCasesPresentationsRoute: typeof UseCasesPresentationsRoute
  UseCasesSalesObjectionsRoute: typeof UseCasesSalesObjectionsRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/win-every-argument': {
      id: '/win-every-argument'
      path: '/win-every-argument'
      fullPath: '/win-every-argument'
      preLoaderRoute: typeof WinEveryArgumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/sales-objections': {
      id: '/use-cases/sales-objections'
      path: '/use-cases/sales-objections'
      fullPath: '/use-cases/sales-objections'
      preLoaderRoute: typeof UseCasesSalesObjectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/presentations': {
      id: '/use-cases/presentations'
      path: '/use-cases/presentations'
      fullPath: '/use-cases/presentations'
      preLoaderRoute: typeof UseCasesPresentationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/politicians-activists': {
      id: '/use-cases/politicians-activists'
      path: '/use-cases/politicians-activists'
      fullPath: '/use-cases/politicians-activists'
      preLoaderRoute: typeof UseCasesPoliticiansActivistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/pitching-fundraising': {
      id: '/use-cases/pitching-fundraising'
      path: '/use-cases/pitching-fundraising'
      fullPath: '/use-cases/pitching-fundraising'
      preLoaderRoute: typeof UseCasesPitchingFundraisingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/parents-educators': {
      id: '/use-cases/parents-educators'
      path: '/use-cases/parents-educators'
      fullPath: '/use-cases/parents-educators'
      preLoaderRoute: typeof UseCasesParentsEducatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/job-interviews': {
      id: '/use-cases/job-interviews'
      path: '/use-cases/job-interviews'
      fullPath: '/use-cases/job-interviews'
      preLoaderRoute: typeof UseCasesJobInterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/healthcare-professionals': {
      id: '/use-cases/healthcare-professionals'
      path: '/use-cases/healthcare-professionals'
      fullPath: '/use-cases/healthcare-professionals'
      preLoaderRoute: typeof UseCasesHealthcareProfessionalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/difficult-conversations': {
      id: '/use-cases/difficult-conversations'
      path: '/use-cases/difficult-conversations'
      fullPath: '/use-cases/difficult-conversations'
      preLoaderRoute: typeof UseCasesDifficultConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/attorneys-legal': {
      id: '/use-cases/attorneys-legal'
      path: '/use-cases/attorneys-legal'
      fullPath: '/use-cases/attorneys-legal'
      preLoaderRoute: typeof UseCasesAttorneysLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/academics-researchers': {
      id: '/use-cases/academics-researchers'
      path: '/use-cases/academics-researchers'
      fullPath: '/use-cases/academics-researchers'
      preLoaderRoute: typeof UseCasesAcademicsResearchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/the-crossed-quills': {
      id: '/blog/the-crossed-quills'
      path: '/blog/the-crossed-quills'
      fullPath: '/blog/the-crossed-quills'
      preLoaderRoute: typeof BlogTheCrossedQuillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/strike-emotional-chord': {
      id: '/blog/strike-emotional-chord'
      path: '/blog/strike-emotional-chord'
      fullPath: '/blog/strike-emotional-chord'
      preLoaderRoute: typeof BlogStrikeEmotionalChordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/stick-the-landing': {
      id: '/blog/stick-the-landing'
      path: '/blog/stick-the-landing'
      fullPath: '/blog/stick-the-landing'
      preLoaderRoute: typeof BlogStickTheLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/spot-the-weakness': {
      id: '/blog/spot-the-weakness'
      path: '/blog/spot-the-weakness'
      fullPath: '/blog/spot-the-weakness'
      preLoaderRoute: typeof BlogSpotTheWeaknessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/scenario-treatment-refusal': {
      id: '/blog/scenario-treatment-refusal'
      path: '/blog/scenario-treatment-refusal'
      fullPath: '/blog/scenario-treatment-refusal'
      preLoaderRoute: typeof BlogScenarioTreatmentRefusalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/scenario-early-customer-sales': {
      id: '/blog/scenario-early-customer-sales'
      path: '/blog/scenario-early-customer-sales'
      fullPath: '/blog/scenario-early-customer-sales'
      preLoaderRoute: typeof BlogScenarioEarlyCustomerSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/scenario-customer-discovery': {
      id: '/blog/scenario-customer-discovery'
      path: '/blog/scenario-customer-discovery'
      fullPath: '/blog/scenario-customer-discovery'
      preLoaderRoute: typeof BlogScenarioCustomerDiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/scenario-contract-negotiation': {
      id: '/blog/scenario-contract-negotiation'
      path: '/blog/scenario-contract-negotiation'
      fullPath: '/blog/scenario-contract-negotiation'
      preLoaderRoute: typeof BlogScenarioContractNegotiationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/read-any-room': {
      id: '/blog/read-any-room'
      path: '/blog/read-any-room'
      fullPath: '/blog/read-any-room'
      preLoaderRoute: typeof BlogReadAnyRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/own-your-weaknesses': {
      id: '/blog/own-your-weaknesses'
      path: '/blog/own-your-weaknesses'
      fullPath: '/blog/own-your-weaknesses'
      preLoaderRoute: typeof BlogOwnYourWeaknessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/make-it-stick': {
      id: '/blog/make-it-stick'
      path: '/blog/make-it-stick'
      fullPath: '/blog/make-it-stick'
      preLoaderRoute: typeof BlogMakeItStickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/land-the-closer': {
      id: '/blog/land-the-closer'
      path: '/blog/land-the-closer'
      fullPath: '/blog/land-the-closer'
      preLoaderRoute: typeof BlogLandTheCloserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/flip-their-momentum': {
      id: '/blog/flip-their-momentum'
      path: '/blog/flip-their-momentum'
      fullPath: '/blog/flip-their-momentum'
      preLoaderRoute: typeof BlogFlipTheirMomentumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/defuse-with-humor': {
      id: '/blog/defuse-with-humor'
      path: '/blog/defuse-with-humor'
      fullPath: '/blog/defuse-with-humor'
      preLoaderRoute: typeof BlogDefuseWithHumorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/cut-through-the-noise': {
      id: '/blog/cut-through-the-noise'
      path: '/blog/cut-through-the-noise'
      fullPath: '/blog/cut-through-the-noise'
      preLoaderRoute: typeof BlogCutThroughTheNoiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/blueprint-part-3': {
      id: '/blog/blueprint-part-3'
      path: '/blog/blueprint-part-3'
      fullPath: '/blog/blueprint-part-3'
      preLoaderRoute: typeof BlogBlueprintPart3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/blueprint-part-2': {
      id: '/blog/blueprint-part-2'
      path: '/blog/blueprint-part-2'
      fullPath: '/blog/blueprint-part-2'
      preLoaderRoute: typeof BlogBlueprintPart2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/blueprint-part-1': {
      id: '/blog/blueprint-part-1'
      path: '/blog/blueprint-part-1'
      fullPath: '/blog/blueprint-part-1'
      preLoaderRoute: typeof BlogBlueprintPart1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/back-it-up': {
      id: '/blog/back-it-up'
      path: '/blog/back-it-up'
      fullPath: '/blog/back-it-up'
      preLoaderRoute: typeof BlogBackItUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/ask-the-killer-question': {
      id: '/blog/ask-the-killer-question'
      path: '/blog/ask-the-killer-question'
      fullPath: '/blog/ask-the-killer-question'
      preLoaderRoute: typeof BlogAskTheKillerQuestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_auth': {
      id: '/_app/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppAuthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login/_layout': {
      id: '/_app/login/_layout'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginLayoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/claim/$token': {
      id: '/_app/claim/$token'
      path: '/claim/$token'
      fullPath: '/claim/$token'
      preLoaderRoute: typeof AppClaimTokenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login/_layout/': {
      id: '/_app/login/_layout/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof AppLoginLayoutIndexRouteImport
      parentRoute: typeof AppLoginLayoutRoute
    }
    '/_app/_auth/onboarding/_layout': {
      id: '/_app/_auth/onboarding/_layout'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppAuthOnboardingLayoutRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/dashboard/prep': {
      id: '/_app/_auth/dashboard/prep'
      path: '/dashboard/prep'
      fullPath: '/dashboard/prep'
      preLoaderRoute: typeof AppAuthDashboardPrepRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/dashboard/opponent-profile': {
      id: '/_app/_auth/dashboard/opponent-profile'
      path: '/dashboard/opponent-profile'
      fullPath: '/dashboard/opponent-profile'
      preLoaderRoute: typeof AppAuthDashboardOpponentProfileRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/dashboard/history': {
      id: '/_app/_auth/dashboard/history'
      path: '/dashboard/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof AppAuthDashboardHistoryRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/dashboard/debate': {
      id: '/_app/_auth/dashboard/debate'
      path: '/dashboard/debate'
      fullPath: '/dashboard/debate'
      preLoaderRoute: typeof AppAuthDashboardDebateRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/dashboard/analysis': {
      id: '/_app/_auth/dashboard/analysis'
      path: '/dashboard/analysis'
      fullPath: '/dashboard/analysis'
      preLoaderRoute: typeof AppAuthDashboardAnalysisRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/dashboard/_layout': {
      id: '/_app/_auth/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppAuthDashboardLayoutRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/dashboard/_layout/': {
      id: '/_app/_auth/dashboard/_layout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppAuthDashboardLayoutIndexRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/onboarding/_layout/username': {
      id: '/_app/_auth/onboarding/_layout/username'
      path: '/username'
      fullPath: '/onboarding/username'
      preLoaderRoute: typeof AppAuthOnboardingLayoutUsernameRouteImport
      parentRoute: typeof AppAuthOnboardingLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/settings': {
      id: '/_app/_auth/dashboard/_layout/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/admin': {
      id: '/_app/_auth/dashboard/_layout/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AppAuthDashboardLayoutAdminRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/settings/': {
      id: '/_app/_auth/dashboard/_layout/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsIndexRouteImport
      parentRoute: typeof AppAuthDashboardLayoutSettingsRoute
    }
    '/_app/_auth/dashboard/_layout/settings/research': {
      id: '/_app/_auth/dashboard/_layout/settings/research'
      path: '/research'
      fullPath: '/dashboard/settings/research'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsResearchRouteImport
      parentRoute: typeof AppAuthDashboardLayoutSettingsRoute
    }
    '/_app/_auth/dashboard/_layout/settings/billing': {
      id: '/_app/_auth/dashboard/_layout/settings/billing'
      path: '/billing'
      fullPath: '/dashboard/settings/billing'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsBillingRouteImport
      parentRoute: typeof AppAuthDashboardLayoutSettingsRoute
    }
  }
}

interface AppAuthDashboardLayoutSettingsRouteChildren {
  AppAuthDashboardLayoutSettingsBillingRoute: typeof AppAuthDashboardLayoutSettingsBillingRoute
  AppAuthDashboardLayoutSettingsResearchRoute: typeof AppAuthDashboardLayoutSettingsResearchRoute
  AppAuthDashboardLayoutSettingsIndexRoute: typeof AppAuthDashboardLayoutSettingsIndexRoute
}

const AppAuthDashboardLayoutSettingsRouteChildren: AppAuthDashboardLayoutSettingsRouteChildren =
  {
    AppAuthDashboardLayoutSettingsBillingRoute:
      AppAuthDashboardLayoutSettingsBillingRoute,
    AppAuthDashboardLayoutSettingsResearchRoute:
      AppAuthDashboardLayoutSettingsResearchRoute,
    AppAuthDashboardLayoutSettingsIndexRoute:
      AppAuthDashboardLayoutSettingsIndexRoute,
  }

const AppAuthDashboardLayoutSettingsRouteWithChildren =
  AppAuthDashboardLayoutSettingsRoute._addFileChildren(
    AppAuthDashboardLayoutSettingsRouteChildren,
  )

interface AppAuthDashboardLayoutRouteChildren {
  AppAuthDashboardLayoutAdminRoute: typeof AppAuthDashboardLayoutAdminRoute
  AppAuthDashboardLayoutSettingsRoute: typeof AppAuthDashboardLayoutSettingsRouteWithChildren
  AppAuthDashboardLayoutIndexRoute: typeof AppAuthDashboardLayoutIndexRoute
}

const AppAuthDashboardLayoutRouteChildren: AppAuthDashboardLayoutRouteChildren =
  {
    AppAuthDashboardLayoutAdminRoute: AppAuthDashboardLayoutAdminRoute,
    AppAuthDashboardLayoutSettingsRoute:
      AppAuthDashboardLayoutSettingsRouteWithChildren,
    AppAuthDashboardLayoutIndexRoute: AppAuthDashboardLayoutIndexRoute,
  }

const AppAuthDashboardLayoutRouteWithChildren =
  AppAuthDashboardLayoutRoute._addFileChildren(
    AppAuthDashboardLayoutRouteChildren,
  )

interface AppAuthOnboardingLayoutRouteChildren {
  AppAuthOnboardingLayoutUsernameRoute: typeof AppAuthOnboardingLayoutUsernameRoute
}

const AppAuthOnboardingLayoutRouteChildren: AppAuthOnboardingLayoutRouteChildren =
  {
    AppAuthOnboardingLayoutUsernameRoute: AppAuthOnboardingLayoutUsernameRoute,
  }

const AppAuthOnboardingLayoutRouteWithChildren =
  AppAuthOnboardingLayoutRoute._addFileChildren(
    AppAuthOnboardingLayoutRouteChildren,
  )

interface AppAuthRouteChildren {
  AppAuthDashboardLayoutRoute: typeof AppAuthDashboardLayoutRouteWithChildren
  AppAuthDashboardAnalysisRoute: typeof AppAuthDashboardAnalysisRoute
  AppAuthDashboardDebateRoute: typeof AppAuthDashboardDebateRoute
  AppAuthDashboardHistoryRoute: typeof AppAuthDashboardHistoryRoute
  AppAuthDashboardOpponentProfileRoute: typeof AppAuthDashboardOpponentProfileRoute
  AppAuthDashboardPrepRoute: typeof AppAuthDashboardPrepRoute
  AppAuthOnboardingLayoutRoute: typeof AppAuthOnboardingLayoutRouteWithChildren
}

const AppAuthRouteChildren: AppAuthRouteChildren = {
  AppAuthDashboardLayoutRoute: AppAuthDashboardLayoutRouteWithChildren,
  AppAuthDashboardAnalysisRoute: AppAuthDashboardAnalysisRoute,
  AppAuthDashboardDebateRoute: AppAuthDashboardDebateRoute,
  AppAuthDashboardHistoryRoute: AppAuthDashboardHistoryRoute,
  AppAuthDashboardOpponentProfileRoute: AppAuthDashboardOpponentProfileRoute,
  AppAuthDashboardPrepRoute: AppAuthDashboardPrepRoute,
  AppAuthOnboardingLayoutRoute: AppAuthOnboardingLayoutRouteWithChildren,
}

const AppAuthRouteWithChildren =
  AppAuthRoute._addFileChildren(AppAuthRouteChildren)

interface AppLoginLayoutRouteChildren {
  AppLoginLayoutIndexRoute: typeof AppLoginLayoutIndexRoute
}

const AppLoginLayoutRouteChildren: AppLoginLayoutRouteChildren = {
  AppLoginLayoutIndexRoute: AppLoginLayoutIndexRoute,
}

const AppLoginLayoutRouteWithChildren = AppLoginLayoutRoute._addFileChildren(
  AppLoginLayoutRouteChildren,
)

interface AppRouteChildren {
  AppAuthRoute: typeof AppAuthRouteWithChildren
  AppClaimTokenRoute: typeof AppClaimTokenRoute
  AppLoginLayoutRoute: typeof AppLoginLayoutRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthRoute: AppAuthRouteWithChildren,
  AppClaimTokenRoute: AppClaimTokenRoute,
  AppLoginLayoutRoute: AppLoginLayoutRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  WinEveryArgumentRoute: WinEveryArgumentRoute,
  BlogAskTheKillerQuestionRoute: BlogAskTheKillerQuestionRoute,
  BlogBackItUpRoute: BlogBackItUpRoute,
  BlogBlueprintPart1Route: BlogBlueprintPart1Route,
  BlogBlueprintPart2Route: BlogBlueprintPart2Route,
  BlogBlueprintPart3Route: BlogBlueprintPart3Route,
  BlogCutThroughTheNoiseRoute: BlogCutThroughTheNoiseRoute,
  BlogDefuseWithHumorRoute: BlogDefuseWithHumorRoute,
  BlogFlipTheirMomentumRoute: BlogFlipTheirMomentumRoute,
  BlogLandTheCloserRoute: BlogLandTheCloserRoute,
  BlogMakeItStickRoute: BlogMakeItStickRoute,
  BlogOwnYourWeaknessesRoute: BlogOwnYourWeaknessesRoute,
  BlogReadAnyRoomRoute: BlogReadAnyRoomRoute,
  BlogScenarioContractNegotiationRoute: BlogScenarioContractNegotiationRoute,
  BlogScenarioCustomerDiscoveryRoute: BlogScenarioCustomerDiscoveryRoute,
  BlogScenarioEarlyCustomerSalesRoute: BlogScenarioEarlyCustomerSalesRoute,
  BlogScenarioTreatmentRefusalRoute: BlogScenarioTreatmentRefusalRoute,
  BlogSpotTheWeaknessRoute: BlogSpotTheWeaknessRoute,
  BlogStickTheLandingRoute: BlogStickTheLandingRoute,
  BlogStrikeEmotionalChordRoute: BlogStrikeEmotionalChordRoute,
  BlogTheCrossedQuillsRoute: BlogTheCrossedQuillsRoute,
  UseCasesAcademicsResearchersRoute: UseCasesAcademicsResearchersRoute,
  UseCasesAttorneysLegalRoute: UseCasesAttorneysLegalRoute,
  UseCasesDifficultConversationsRoute: UseCasesDifficultConversationsRoute,
  UseCasesHealthcareProfessionalsRoute: UseCasesHealthcareProfessionalsRoute,
  UseCasesJobInterviewsRoute: UseCasesJobInterviewsRoute,
  UseCasesParentsEducatorsRoute: UseCasesParentsEducatorsRoute,
  UseCasesPitchingFundraisingRoute: UseCasesPitchingFundraisingRoute,
  UseCasesPoliticiansActivistsRoute: UseCasesPoliticiansActivistsRoute,
  UseCasesPresentationsRoute: UseCasesPresentationsRoute,
  UseCasesSalesObjectionsRoute: UseCasesSalesObjectionsRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
